<?php
require_once __DIR__.'/functions.php';
if(session_status() === PHP_SESSION_NONE) session_start();
$error = null;
$success = null;
$selectedEventId = (int)($_GET['event'] ?? 0);
if($_SERVER['REQUEST_METHOD'] === 'POST' && empty($_POST) && (int)($_SERVER['CONTENT_LENGTH'] ?? 0) > parseIniSizeBytes(ini_get('post_max_size'))){
  $error = 'Ukuran upload melewati batas request PHP (post_max_size '.ini_get('post_max_size').'). Naikkan batas PHP lalu mulai ulang server.';
}elseif($_SERVER['REQUEST_METHOD'] === 'POST'){
  try{
    if(!csrf_verify($_POST['csrf'] ?? '')) throw new RuntimeException('Token keamanan tidak valid. Muat ulang halaman dan coba lagi.');
    if(empty($_SESSION['customer_id'])) throw new RuntimeException('Masuk ke akun pelanggan terlebih dahulu.');
    if(($_POST['action'] ?? '') === 'submit_diy'){
      submitDiyVideo($_FILES['video'] ?? [], $_POST, $_SESSION['customer_id'], $_SESSION['customer_name'] ?? 'Pelanggan');
      $success = 'Video terkirim untuk moderasi. Poin diberikan setelah karya disetujui.';
    }elseif(($_POST['action'] ?? '') === 'place_bid'){
      placeAuctionBid((int)($_POST['auction_id'] ?? 0), $_SESSION['customer_id'], $_SESSION['customer_name'] ?? 'Pelanggan', (int)($_POST['bid_amount'] ?? 0));
      $success = 'Penawaran kamu sudah tercatat.';
    }elseif(($_POST['action'] ?? '') === 'school_mission'){
      submitSchoolMission($_POST, $_SESSION['customer_id'], $_SESSION['customer_name'] ?? 'Pelanggan');
      $selectedEventId = (int)$_POST['event_id'];
      $success = 'Misi sekolah terkirim untuk verifikasi admin.';
    }
  }catch(Throwable $e){ $error = $e->getMessage(); }
}
$resources = getDiyResources();
$auctions = getCommunityAuctions();
$buyerRanks = getBuyerLeaderboard();
$sellerRanks = getSellerLeaderboard();
$events = getSchoolEvents();
$videoUploadLimit = min(50 * 1024 * 1024, getEffectiveVideoUploadLimit());
if(!$selectedEventId && $events) $selectedEventId = (int)$events[0]['id'];
$schoolRanks = $selectedEventId ? getSchoolLeaderboard($selectedEventId) : [];
$auctionOrders = !empty($_SESSION['customer_id']) ? getCustomerAuctionOrders($_SESSION['customer_id']) : [];
$auctionPaymentLinks = [];
$adminWhatsApp = defined('WHATSAPP_PHONE') ? WHATSAPP_PHONE : '6287874872257';
foreach($auctionOrders as $auctionOrder){
  if($auctionOrder['payment_status'] === 'pending'){
    $message = 'Halo Terra Kala, saya pemenang lelang '.$auctionOrder['auction_title'].'. Nomor order '.$auctionOrder['order_no'].', total '.$auctionOrder['total'].'. Mohon instruksi pembayaran.';
    $auctionPaymentLinks[$auctionOrder['order_no']] = 'https://api.whatsapp.com/send/?phone='.$adminWhatsApp.'&text='.rawurlencode($message).'&type=phone_number&app_absent=0';
  }
}
include __DIR__.'/header.php';
?>
<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4">
  <div><p class="text-success fw-bold mb-1">TERRA KALA / KOMUNITAS</p><h1 class="mb-0">Belajar, berkarya, hidup lebih sirkular.</h1></div>
  <nav class="d-flex flex-wrap gap-2" aria-label="Navigasi komunitas"><a class="btn btn-sm btn-outline-success" href="#diy">DIY</a><a class="btn btn-sm btn-outline-success" href="#auction">Lelang</a><a class="btn btn-sm btn-outline-success" href="#ranking">Peringkat</a><a class="btn btn-sm btn-outline-success" href="#schools">Sekolah</a></nav>
</div>
<?php if($error): ?><div class="alert alert-danger"><?php echo esc($error); ?></div><?php endif; ?>
<?php if($success): ?><div class="alert alert-success"><?php echo esc($success); ?></div><?php endif; ?>

<section id="diy" class="mb-5">
  <h2>Panduan DIY</h2><p class="text-muted">Resep kreatif dan cara mengubah barang bekas jadi berguna.</p>
  <?php if($resources): ?><div class="row g-3 mb-4"><?php foreach($resources as $resource): ?><div class="col-md-6 col-xl-4"><article class="card h-100 p-3"><span class="badge text-bg-success align-self-start"><?php echo $resource['resource_type'] === 'ebook' ? 'Buku digital' : 'Video panduan'; ?></span><h3 class="h5 mt-3"><?php echo esc($resource['title']); ?></h3><p class="text-muted flex-grow-1"><?php echo nl2br(esc($resource['description'])); ?></p><a class="btn btn-outline-success align-self-start" href="<?php echo esc($resource['resource_url']); ?>" target="_blank" rel="noopener">Buka panduan <i class="fa fa-arrow-up-right-from-square ms-1"></i></a></article></div><?php endforeach; ?></div><?php else: ?><p class="text-muted">Panduan baru akan segera hadir.</p><?php endif; ?>
  <div class="card p-3"><div class="row g-3 align-items-center"><div class="col-lg-4"><h3 class="h4">Bagikan karya guna ulangmu</h3><p class="text-muted mb-lg-0">Video maksimal <?php echo esc(formatFileSize($videoUploadLimit)); ?> sesuai batas server saat ini (maksimal fitur 50 MB). Karya yang lolos moderasi mendapat poin hadiah.</p></div><div class="col-lg-8">
    <?php if(!empty($_SESSION['customer_id'])): ?><form method="post" enctype="multipart/form-data" class="row g-2"><input type="hidden" name="csrf" value="<?php echo esc(csrf_token()); ?>"><input type="hidden" name="action" value="submit_diy"><div class="col-md-6"><label class="form-label">Judul karya</label><input class="form-control" name="title" maxlength="180" required></div><div class="col-md-6"><label class="form-label">Asal sekolah (opsional)</label><input class="form-control" name="school_name" maxlength="180"></div><div class="col-md-8"><label class="form-label">Cerita proses</label><textarea class="form-control" name="description" rows="2"></textarea></div><div class="col-md-4"><label class="form-label">Video (MP4/WebM/MOV)</label><input class="form-control" type="file" name="video" accept="video/mp4,video/webm,video/quicktime" required><div class="form-text">Maks. <?php echo esc(formatFileSize($videoUploadLimit)); ?></div></div><div class="col-12"><button class="btn btn-success"><i class="fa fa-upload me-1"></i>Kirim karya</button></div></form><?php else: ?><a class="btn btn-success" href="customer_login.php?next=community.php">Masuk untuk mengirim karya</a><?php endif; ?>
  </div></div></div>
</section>

<section id="auction" class="mb-5"><div class="d-flex flex-wrap justify-content-between align-items-end mb-3"><div><h2>Lelang preloved dan upcycle</h2><p class="text-muted mb-0">Barang pilihan yang masih layak digunakan dan karya dengan material guna ulang.</p></div><span class="small text-muted">Kenaikan minimum tercantum pada setiap lelang.</span></div>
  <?php if($auctions): ?><div class="row g-3"><?php foreach($auctions as $auction): $now=date('Y-m-d H:i:s'); $isOpen=$now >= $auction['starts_at'] && $now < $auction['ends_at']; $minimumBid=(int)$auction['current_bid']+((int)$auction['bid_count']>0?(int)$auction['min_increment']:0); $minimumBid=max(1,$minimumBid); ?><div class="col-lg-6"><article class="card h-100 overflow-hidden">
    <?php if($auction['image_url']): ?><img src="<?php echo esc($auction['image_url']); ?>" alt="<?php echo esc($auction['title']); ?>" style="width:100%;height:240px;object-fit:cover"><?php endif; ?><div class="p-3"><div class="d-flex justify-content-between gap-3"><h3 class="h4"><?php echo esc($auction['title']); ?></h3><span class="badge <?php echo $isOpen?'text-bg-success':'text-bg-secondary'; ?> align-self-start"><?php echo $isOpen?'Berlangsung':($now<$auction['starts_at']?'Segera':'Selesai'); ?></span></div><p><?php echo nl2br(esc($auction['description'])); ?></p><div class="d-flex flex-wrap gap-4 small"><span>Penawaran tertinggi <strong><?php echo formatRupiah($auction['current_bid']); ?></strong></span><span><?php echo (int)$auction['bid_count']; ?> penawaran</span><span>Berakhir <?php echo esc(date('d/m/Y H:i',strtotime($auction['ends_at']))); ?></span></div>
    <?php if($isOpen): ?><?php if(!empty($_SESSION['customer_id'])): ?><form method="post" class="d-flex gap-2 mt-3"><input type="hidden" name="csrf" value="<?php echo esc(csrf_token()); ?>"><input type="hidden" name="action" value="place_bid"><input type="hidden" name="auction_id" value="<?php echo (int)$auction['id']; ?>"><input class="form-control" type="number" min="<?php echo $minimumBid; ?>" step="1000" name="bid_amount" placeholder="Min. <?php echo formatRupiah($minimumBid); ?>" required><button class="btn btn-success text-nowrap"><i class="fa fa-gavel me-1"></i>Tawar</button></form><?php else: ?><a class="btn btn-outline-success mt-3" href="customer_login.php?next=community.php#auction">Masuk untuk menawar</a><?php endif; ?><?php endif; ?>
  </div></article></div><?php endforeach; ?></div><?php else: ?><div class="border-top border-bottom py-4 text-muted">Belum ada lelang yang dijadwalkan.</div><?php endif; ?>
</section>

<?php if($auctionOrders): ?><section class="mb-5"><h2 class="h3">Lelang yang kamu menangkan</h2><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Barang</th><th>Nomor order</th><th class="text-end">Tagihan</th><th>Status</th><th>Aksi</th></tr></thead><tbody><?php foreach($auctionOrders as $auctionOrder): ?><tr><td><?php echo esc($auctionOrder['auction_title']); ?></td><td><?php echo esc($auctionOrder['order_no']); ?></td><td class="text-end"><?php echo formatRupiah($auctionOrder['total']); ?></td><td><?php echo esc($auctionOrder['payment_status']); ?></td><td><?php if($auctionOrder['payment_status']==='pending'): ?><a class="btn btn-sm btn-success" href="<?php echo esc($auctionPaymentLinks[$auctionOrder['order_no']]); ?>" target="_blank" rel="noopener"><i class="fa-brands fa-whatsapp me-1"></i>Instruksi pembayaran</a><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div><p class="small text-muted">Admin memverifikasi pembayaran secara manual. Poin pembeli diberikan setelah status order lunas.</p></section><?php endif; ?>

<section id="ranking" class="mb-5"><h2>Papan peringkat</h2><div class="row g-4">
  <div class="col-lg-6"><h3 class="h5">Pembeli aktif</h3><p class="small text-muted">Poin tercatat dari transaksi yang lunas. Lima poin dapat ditukar menjadi voucher.</p><div class="table-responsive"><table class="table table-sm align-middle"><thead><tr><th>#</th><th>Pelanggan</th><th class="text-end">Transaksi</th><th class="text-end">Belanja</th><th class="text-end">Poin</th></tr></thead><tbody><?php foreach($buyerRanks as $i=>$buyer): ?><tr><td><?php echo $i+1; ?></td><td><?php echo esc($buyer['name']); ?></td><td class="text-end"><?php echo (int)$buyer['order_count']; ?></td><td class="text-end"><?php echo formatRupiah($buyer['spend_total']); ?></td><td class="text-end fw-bold"><?php echo (int)$buyer['points_total']; ?></td></tr><?php endforeach; ?><?php if(!$buyerRanks): ?><tr><td colspan="5" class="text-muted">Belum ada transaksi.</td></tr><?php endif; ?></tbody></table></div></div>
  <div class="col-lg-6"><h3 class="h5">Seller triwulan berjalan</h3><p class="small text-muted">Peringkat melihat produk baru dan nilai penjualan yang sudah lunas. Tiga teratas mendapat 500, 300, dan 150 poin setelah triwulan ditutup.</p><div class="table-responsive"><table class="table table-sm align-middle"><thead><tr><th>#</th><th>Seller</th><th class="text-end">Produk baru</th><th class="text-end">Terjual</th><th class="text-end">Bonus</th><th class="text-end">Saldo</th></tr></thead><tbody><?php foreach($sellerRanks['rows'] as $i=>$seller): ?><tr><td><?php echo $i+1; ?></td><td><?php echo esc($seller['name']); ?></td><td class="text-end"><?php echo (int)$seller['products_created']; ?></td><td class="text-end"><?php echo (int)$seller['units_sold']; ?></td><td class="text-end fw-bold"><?php echo (int)$seller['bonus_points']; ?></td><td class="text-end"><?php echo (int)$seller['bonus_points_balance']; ?></td></tr><?php endforeach; ?><?php if(!$sellerRanks['rows']): ?><tr><td colspan="6" class="text-muted">Belum ada seller aktif.</td></tr><?php endif; ?></tbody></table></div><div class="small text-muted">Periode: <?php echo esc($sellerRanks['period']); ?></div></div>
</div></section>

<section id="schools" class="mb-5"><div class="d-flex flex-wrap justify-content-between align-items-end gap-2 mb-3"><div><h2>Kompetisi antar-sekolah</h2><p class="text-muted mb-0">Misi berkala untuk mengumpulkan skor tim. Tiga tim teratas mendapat hadiah event.</p></div><?php if($events): ?><form method="get"><label class="visually-hidden" for="event-select">Pilih event</label><select class="form-select" id="event-select" name="event" onchange="this.form.submit()"><?php foreach($events as $event): ?><option value="<?php echo (int)$event['id']; ?>" <?php echo $selectedEventId===(int)$event['id']?'selected':''; ?>><?php echo esc($event['name']); ?></option><?php endforeach; ?></select></form><?php endif; ?></div>
<?php $selectedEvent=null; foreach($events as $event){if((int)$event['id']===$selectedEventId)$selectedEvent=$event;} ?>
<?php if($selectedEvent): ?><div class="row g-4"><div class="col-lg-6"><p><?php echo nl2br(esc($selectedEvent['description'])); ?></p><p class="small text-muted"><?php echo esc(date('d/m/Y',strtotime($selectedEvent['starts_at']))); ?> - <?php echo esc(date('d/m/Y',strtotime($selectedEvent['ends_at']))); ?><?php if($selectedEvent['top_prize']): ?> · Hadiah: <?php echo esc($selectedEvent['top_prize']); ?><?php endif; ?></p>
  <?php $eventOpen=date('Y-m-d H:i:s') >= $selectedEvent['starts_at'] && date('Y-m-d H:i:s') < $selectedEvent['ends_at']; if(!empty($_SESSION['customer_id']) && $eventOpen): ?><form method="post" class="row g-2"><input type="hidden" name="csrf" value="<?php echo esc(csrf_token()); ?>"><input type="hidden" name="action" value="school_mission"><input type="hidden" name="event_id" value="<?php echo $selectedEventId; ?>"><div class="col-sm-6"><label class="form-label">Sekolah</label><input class="form-control" name="school_name" required></div><div class="col-sm-6"><label class="form-label">Nama tim</label><input class="form-control" name="team_name" required></div><div class="col-12"><label class="form-label">Misi/karya yang diselesaikan</label><textarea class="form-control" name="mission_description" rows="3" required></textarea></div><div class="col-12"><button class="btn btn-success">Kirim misi</button></div></form><?php elseif(empty($_SESSION['customer_id']) && $eventOpen): ?><a href="customer_login.php?next=community.php#schools" class="btn btn-outline-success">Masuk untuk ikut</a><?php endif; ?></div>
  <div class="col-lg-6"><h3 class="h5">Skor tim</h3><table class="table table-sm"><thead><tr><th>#</th><th>Sekolah / Tim</th><th class="text-end">Skor</th></tr></thead><tbody><?php foreach($schoolRanks as $i=>$rank): ?><tr><td><?php echo $i+1; ?></td><td><?php echo esc($rank['school_name']); ?> <span class="text-muted">/ <?php echo esc($rank['team_name']); ?></span></td><td class="text-end fw-bold"><?php echo (int)$rank['score']; ?></td></tr><?php endforeach; ?><?php if(!$schoolRanks): ?><tr><td colspan="3" class="text-muted">Skor tampil setelah misi diverifikasi.</td></tr><?php endif; ?></tbody></table></div></div><?php else: ?><div class="border-top border-bottom py-4 text-muted">Belum ada kompetisi aktif.</div><?php endif; ?></section>
<?php if($selectedEvent): $schoolAwards=getSchoolAwards($selectedEventId); if($schoolAwards): ?><section class="mb-5"><h2>Podium dan hadiah</h2><div class="table-responsive"><table class="table"><thead><tr><th>Peringkat</th><th>Sekolah / Tim</th><th>Hadiah</th><th>Status hadiah</th></tr></thead><tbody><?php foreach($schoolAwards as $award): ?><tr><td><?php echo (int)$award['rank_position']; ?></td><td><?php echo esc($award['school_name'].' / '.$award['team_name']); ?></td><td><?php echo esc($award['prize'] ?: 'Hadiah event'); ?></td><td><?php echo $award['award_status']==='awarded'?'Diserahkan':'Menunggu penyerahan'; ?></td></tr><?php endforeach; ?></tbody></table></div></section><?php endif; endif; ?>
<?php include __DIR__.'/footer.php'; ?>