<?php
require_once __DIR__.'/../functions.php';
if(session_status() === PHP_SESSION_NONE) session_start();
require_once __DIR__.'/auth.php';
$error = null;
try{
  if($_SERVER['REQUEST_METHOD'] === 'POST'){
    if(!csrf_verify($_POST['csrf'] ?? '')) throw new RuntimeException('Token CSRF tidak valid.');
    $action = $_POST['action'] ?? '';
    if($action === 'resource') addDiyResource($_POST);
    elseif($action === 'auction') addCommunityAuction($_POST);
    elseif($action === 'event') addSchoolEvent($_POST);
    elseif($action === 'score') saveSchoolScore((int)$_POST['event_id'], $_POST['school_name'], $_POST['team_name'], (int)$_POST['score']);
    elseif($action === 'review_diy') reviewDiySubmission((int)$_POST['submission_id'], $_POST['decision'], (int)($_POST['points'] ?? 0));
    elseif($action === 'review_school') reviewSchoolSubmission((int)$_POST['submission_id'], $_POST['decision'] === 'approved', (int)($_POST['score'] ?? 0));
    elseif($action === 'toggle') setCommunityRecordActive($_POST['table'], (int)$_POST['id'], (int)$_POST['active']);
    elseif($action === 'settle_auction') settleAuction((int)$_POST['auction_id']);
    elseif($action === 'finalize_school') finalizeSchoolEvent((int)$_POST['event_id']);
    elseif($action === 'deliver_award') markSchoolAwardDelivered((int)$_POST['award_id']);
    elseif($action === 'settle_seller_quarter') settleSellerQuarter($_POST['quarter_start'] ?? '');
    else throw new RuntimeException('Aksi tidak dikenal.');
    header('Location: community.php?msg=saved'); exit;
  }
}catch(Throwable $e){ $error = $e->getMessage(); }
$resources = getDiyResources(false);
$auctions = getCommunityAuctions(false);
$events = getSchoolEvents(false);
$pendingDiy = getPendingCommunitySubmissions();
$pendingSchool = getPendingSchoolSubmissions();
$auctionSettlements = getAuctionSettlements();
$sellerBonusAwards = getSellerBonusAwards();
$schoolAwardsByEvent = [];
foreach($events as $event){ $schoolAwardsByEvent[(int)$event['id']] = getSchoolAwards($event['id']); }
include __DIR__.'/../header.php';
?>
<div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-4"><div><h1>Kelola Komunitas</h1><p class="text-muted mb-0">Panduan guna ulang dan upcycle, lelang preloved, serta kegiatan edukasi lingkungan.</p></div><a href="products.php" class="btn btn-outline-secondary"><i class="fa fa-arrow-left me-1"></i>Admin utama</a></div>
<?php if($error): ?><div class="alert alert-danger"><?php echo esc($error); ?></div><?php endif; ?><?php if(isset($_GET['msg'])): ?><div class="alert alert-success">Perubahan berhasil disimpan.</div><?php endif; ?>
<section class="card p-3 mb-4"><div class="d-flex flex-wrap justify-content-between align-items-center gap-3"><div><h2 class="h4 mb-1">Settlement bonus seller</h2><p class="text-muted small mb-0">Tutup triwulan yang berakhir; bonus hanya dapat diberikan sekali per periode.</p></div><form method="post" class="d-flex gap-2"><input type="hidden" name="csrf" value="<?php echo esc(csrf_token()); ?>"><input type="hidden" name="action" value="settle_seller_quarter"><select class="form-select" name="quarter_start" required><?php $quarterMonth=intdiv((int)date('n')-1,3)*3+1; $quarterCursor=sprintf('%04d-%02d-01',(int)date('Y'),$quarterMonth); for($q=0;$q<12;$q++): $quarterCursor=date('Y-m-d',strtotime($quarterCursor.' -3 months')); ?><option value="<?php echo esc($quarterCursor); ?>">Q<?php echo intdiv((int)date('n',strtotime($quarterCursor))-1,3)+1; ?> <?php echo date('Y',strtotime($quarterCursor)); ?></option><?php endfor; ?></select><button class="btn btn-primary text-nowrap">Tutup periode</button></form></div>
<?php if($sellerBonusAwards): ?><div class="table-responsive mt-3"><table class="table table-sm mb-0"><thead><tr><th>Periode mulai</th><th>Seller</th><th>Poin bonus</th><th>Diproses</th></tr></thead><tbody><?php foreach($sellerBonusAwards as $award): ?><tr><td><?php echo esc($award['quarter_start']); ?></td><td><?php echo esc($award['seller_name']); ?></td><td><?php echo (int)$award['points']; ?></td><td><?php echo esc($award['created_at']); ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section>
<div class="row g-3 mb-4">
  <div class="col-lg-4"><section class="card p-3 h-100"><h2 class="h4">Tambah panduan DIY</h2><form method="post" class="row g-2"><input type="hidden" name="csrf" value="<?php echo esc(csrf_token()); ?>"><input type="hidden" name="action" value="resource"><div class="col-12"><label class="form-label">Judul</label><input class="form-control" name="title" required maxlength="180"></div><div class="col-12"><label class="form-label">Jenis</label><select class="form-select" name="resource_type"><option value="video">Video</option><option value="ebook">Buku digital</option></select></div><div class="col-12"><label class="form-label">URL video/PDF</label><input class="form-control" type="url" name="resource_url" required maxlength="500"></div><div class="col-12"><label class="form-label">Deskripsi</label><textarea class="form-control" name="description" rows="2"></textarea></div><div class="col-12"><button class="btn btn-success">Publikasikan</button></div></form></section></div>
  <div class="col-lg-4"><section class="card p-3 h-100"><h2 class="h4">Buat lelang</h2><form method="post" class="row g-2"><input type="hidden" name="csrf" value="<?php echo esc(csrf_token()); ?>"><input type="hidden" name="action" value="auction"><div class="col-12"><label class="form-label">Nama barang</label><input class="form-control" name="title" required maxlength="180"></div><div class="col-12"><label class="form-label">Foto URL (opsional)</label><input class="form-control" type="url" name="image_url"></div><div class="col-6"><label class="form-label">Mulai</label><input class="form-control" type="datetime-local" name="starts_at" required></div><div class="col-6"><label class="form-label">Berakhir</label><input class="form-control" type="datetime-local" name="ends_at" required></div><div class="col-6"><label class="form-label">Harga awal</label><input class="form-control" type="number" name="starting_bid" min="1" required></div><div class="col-6"><label class="form-label">Kenaikan minimum</label><input class="form-control" type="number" name="min_increment" min="1000" value="10000" required></div><div class="col-12"><label class="form-label">Deskripsi</label><textarea class="form-control" name="description" rows="2"></textarea></div><div class="col-12"><button class="btn btn-success">Jadwalkan lelang</button></div></form></section></div>
  <div class="col-lg-4"><section class="card p-3 h-100"><h2 class="h4">Buat kompetisi sekolah</h2><form method="post" class="row g-2"><input type="hidden" name="csrf" value="<?php echo esc(csrf_token()); ?>"><input type="hidden" name="action" value="event"><div class="col-12"><label class="form-label">Nama event</label><input class="form-control" name="name" required maxlength="180"></div><div class="col-6"><label class="form-label">Mulai</label><input class="form-control" type="datetime-local" name="starts_at" required></div><div class="col-6"><label class="form-label">Berakhir</label><input class="form-control" type="datetime-local" name="ends_at" required></div><div class="col-12"><label class="form-label">Hadiah 3 besar</label><input class="form-control" name="top_prize"></div><div class="col-12"><label class="form-label">Deskripsi misi</label><textarea class="form-control" name="description" rows="2"></textarea></div><div class="col-12"><button class="btn btn-success">Buat event</button></div></form></section></div>
</div>

<section class="mb-4"><h2 class="h3">Moderasi karya DIY <span class="badge text-bg-secondary"><?php echo count($pendingDiy); ?></span></h2>
<?php if($pendingDiy): ?><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Karya</th><th>Pembuat</th><th>Sekolah</th><th>Video</th><th>Keputusan</th></tr></thead><tbody><?php foreach($pendingDiy as $submission): ?><tr><td><strong><?php echo esc($submission['title']); ?></strong><div class="small text-muted"><?php echo esc($submission['description']); ?></div></td><td><?php echo esc($submission['customer_name']); ?></td><td><?php echo esc($submission['school_name'] ?: '-'); ?></td><td><a href="../<?php echo esc($submission['video_path']); ?>" target="_blank" rel="noopener">Tonton</a></td><td><form method="post" class="d-flex flex-wrap gap-2 align-items-center"><input type="hidden" name="csrf" value="<?php echo esc(csrf_token()); ?>"><input type="hidden" name="action" value="review_diy"><input type="hidden" name="submission_id" value="<?php echo (int)$submission['id']; ?>"><input class="form-control form-control-sm" style="width:90px" type="number" name="points" min="0" value="5" aria-label="Poin hadiah"><button class="btn btn-sm btn-success" name="decision" value="approved">Setujui</button><button class="btn btn-sm btn-outline-danger" name="decision" value="rejected">Tolak</button></form></td></tr><?php endforeach; ?></tbody></table></div><?php else: ?><p class="text-muted">Tidak ada karya menunggu moderasi.</p><?php endif; ?></section>

<section class="mb-4"><h2 class="h3">Moderasi misi sekolah <span class="badge text-bg-secondary"><?php echo count($pendingSchool); ?></span></h2>
<?php if($pendingSchool): ?><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Event</th><th>Sekolah / Tim</th><th>Peserta</th><th>Misi</th><th>Keputusan</th></tr></thead><tbody><?php foreach($pendingSchool as $submission): ?><tr><td><?php echo esc($submission['event_name']); ?></td><td><?php echo esc($submission['school_name'].' / '.$submission['team_name']); ?></td><td><?php echo esc($submission['customer_name']); ?></td><td><?php echo nl2br(esc($submission['mission_description'])); ?></td><td><form method="post" class="d-flex gap-2"><input type="hidden" name="csrf" value="<?php echo esc(csrf_token()); ?>"><input type="hidden" name="action" value="review_school"><input type="hidden" name="submission_id" value="<?php echo (int)$submission['id']; ?>"><input class="form-control form-control-sm" style="width:90px" type="number" name="score" min="0" value="10" aria-label="Skor misi"><button class="btn btn-sm btn-success" name="decision" value="approved">Setujui</button><button class="btn btn-sm btn-outline-danger" name="decision" value="rejected">Tolak</button></form></td></tr><?php endforeach; ?></tbody></table></div><?php else: ?><p class="text-muted">Tidak ada misi menunggu verifikasi.</p><?php endif; ?></section>

<div class="row g-4"><div class="col-lg-6"><section><h2 class="h3">Materi terbit</h2><?php foreach($resources as $row): ?><div class="d-flex justify-content-between align-items-center border-bottom py-2"><span><?php echo esc($row['title']); ?> <small class="text-muted">(<?php echo esc($row['resource_type']); ?>)</small></span><form method="post"><input type="hidden" name="csrf" value="<?php echo esc(csrf_token()); ?>"><input type="hidden" name="action" value="toggle"><input type="hidden" name="table" value="diy_resources"><input type="hidden" name="id" value="<?php echo (int)$row['id']; ?>"><input type="hidden" name="active" value="0"><button class="btn btn-sm btn-outline-danger">Nonaktifkan</button></form></div><?php endforeach; ?><?php if(!$resources): ?><p class="text-muted">Belum ada panduan.</p><?php endif; ?></section></div>
<div class="col-lg-6"><section><h2 class="h3">Atur skor tim</h2><form method="post" class="row g-2 mb-3"><input type="hidden" name="csrf" value="<?php echo esc(csrf_token()); ?>"><input type="hidden" name="action" value="score"><div class="col-12"><label class="form-label">Event</label><select class="form-select" name="event_id" required><?php foreach($events as $event): ?><option value="<?php echo (int)$event['id']; ?>"><?php echo esc($event['name']); ?></option><?php endforeach; ?></select></div><div class="col-md-4"><label class="form-label">Sekolah</label><input class="form-control" name="school_name" required></div><div class="col-md-4"><label class="form-label">Tim</label><input class="form-control" name="team_name" required></div><div class="col-md-4"><label class="form-label">Skor total</label><input class="form-control" type="number" name="score" min="0" required></div><div class="col-12"><button class="btn btn-primary" <?php echo !$events?'disabled':''; ?>>Simpan skor</button></div></form></section></div></div>
<section class="mt-4"><h2 class="h3">Lelang terjadwal</h2><?php foreach($auctions as $row): ?><div class="d-flex justify-content-between align-items-center border-bottom py-2"><span><?php echo esc($row['title']); ?> <small class="text-muted"><?php echo esc($row['starts_at'].' - '.$row['ends_at']); ?></small></span><?php if($row['is_active']): ?><form method="post"><input type="hidden" name="csrf" value="<?php echo esc(csrf_token()); ?>"><input type="hidden" name="action" value="toggle"><input type="hidden" name="table" value="auctions"><input type="hidden" name="id" value="<?php echo (int)$row['id']; ?>"><input type="hidden" name="active" value="0"><button class="btn btn-sm btn-outline-danger">Nonaktifkan</button></form><?php else: ?><span class="badge text-bg-secondary">Nonaktif</span><?php endif; ?></div><?php endforeach; ?><?php if(!$auctions): ?><p class="text-muted">Belum ada lelang.</p><?php endif; ?></section>
<section class="mt-4"><h2 class="h3">Pemenang dan pembayaran lelang</h2><?php if($auctionSettlements): ?><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Lelang</th><th>Pemenang</th><th>Penawaran</th><th>Order</th><th>Status pembayaran</th></tr></thead><tbody><?php foreach($auctionSettlements as $settlement): ?><tr><td><?php echo esc($settlement['auction_title']); ?></td><td><?php echo esc($settlement['winner_name'] ?: '-'); ?></td><td><?php echo formatRupiah($settlement['winning_bid']); ?></td><td><?php echo esc($settlement['order_no'] ?: '-'); ?></td><td><?php echo esc($settlement['payment_status'] ?: $settlement['settlement_status']); ?></td></tr><?php endforeach; ?></tbody></table></div><?php else: ?><p class="text-muted">Belum ada lelang yang diselesaikan.</p><?php endif; ?></section>
<section class="mt-4"><h2 class="h3">Tutup lelang berakhir</h2><?php $settledAuctionIds=array_map('intval',array_column($auctionSettlements,'auction_id')); $closableAuctions=array_filter($auctions,function($row)use($settledAuctionIds){return $row['ends_at']<=date('Y-m-d H:i:s') && !in_array((int)$row['id'],$settledAuctionIds,true);}); ?><?php if($closableAuctions): ?><?php foreach($closableAuctions as $row): ?><form method="post" class="d-flex justify-content-between align-items-center border-bottom py-2"><span><?php echo esc($row['title']); ?> <small class="text-muted">Tawaran tertinggi: <?php echo formatRupiah($row['current_bid']); ?></small></span><input type="hidden" name="csrf" value="<?php echo esc(csrf_token()); ?>"><input type="hidden" name="action" value="settle_auction"><input type="hidden" name="auction_id" value="<?php echo (int)$row['id']; ?>"><button class="btn btn-sm btn-success">Tutup & buat order pemenang</button></form><?php endforeach; ?><?php else: ?><p class="text-muted">Tidak ada lelang yang menunggu penutupan.</p><?php endif; ?></section>
<section class="mt-4"><h2 class="h3">Pemenang kompetisi dan hadiah</h2><?php foreach($events as $row): $eventAwards=$schoolAwardsByEvent[(int)$row['id']] ?? []; ?><div class="border-bottom py-3"><div class="d-flex justify-content-between align-items-center gap-2"><div><strong><?php echo esc($row['name']); ?></strong><div class="small text-muted"><?php echo esc($row['starts_at'].' - '.$row['ends_at']); ?></div></div><?php if(empty($row['is_finalized']) && $row['ends_at']<=date('Y-m-d H:i:s')): ?><form method="post"><input type="hidden" name="csrf" value="<?php echo esc(csrf_token()); ?>"><input type="hidden" name="action" value="finalize_school"><input type="hidden" name="event_id" value="<?php echo (int)$row['id']; ?>"><button class="btn btn-sm btn-success">Tutup event & tetapkan 3 besar</button></form><?php elseif(!empty($row['is_finalized']) && !$eventAwards): ?><span class="badge text-bg-secondary">Tidak ada tim berskor</span><?php endif; ?></div>
<?php if($eventAwards): ?><div class="table-responsive mt-2"><table class="table table-sm mb-0"><thead><tr><th>Peringkat</th><th>Sekolah / Tim</th><th>Hadiah</th><th>Status</th><th>Aksi</th></tr></thead><tbody><?php foreach($eventAwards as $award): ?><tr><td><?php echo (int)$award['rank_position']; ?></td><td><?php echo esc($award['school_name'].' / '.$award['team_name']); ?></td><td><?php echo esc($award['prize'] ?: 'Hadiah event'); ?></td><td><?php echo esc($award['award_status']); ?></td><td><?php if($award['award_status']==='pending'): ?><form method="post"><input type="hidden" name="csrf" value="<?php echo esc(csrf_token()); ?>"><input type="hidden" name="action" value="deliver_award"><input type="hidden" name="award_id" value="<?php echo (int)$award['id']; ?>"><button class="btn btn-sm btn-outline-success">Catat hadiah diserahkan</button></form><?php else: ?><?php echo esc($award['awarded_at']); ?><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></div><?php endforeach; ?></section>
<?php include __DIR__.'/../footer.php'; ?>